pub mod api;

// Generated by flutter_rust_bridge. The domain crate remains `forbid(unsafe_code)`;
// FFI glue is isolated here because generated native bindings necessarily cross an unsafe ABI.
mod frb_generated;
