#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$ROOT/apps/unitflow_app"
BRIDGE="$ROOT/crates/unitflow_bridge"

if ! command -v flutter_rust_bridge_codegen >/dev/null 2>&1; then
  echo "flutter_rust_bridge_codegen is required." >&2
  echo "Install the pinned generator with:" >&2
  echo "  cargo install flutter_rust_bridge_codegen --version 2.12.0 --locked" >&2
  exit 1
fi

# Cargokit is the stable/default integration backend for flutter_rust_bridge 2.12.0.
# Native Assets requires a later FRB generation and is intentionally not selected here.
cd "$APP"
flutter_rust_bridge_codegen integrate \
  --rust-crate-name unitflow_bridge \
  --rust-crate-dir ../../crates/unitflow_bridge \
  --integration-backend cargokit \
  --platforms android,ios,linux,macos,windows \
  --no-write-lib \
  --no-integration-test \
  --no-dart-fix \
  --no-dart-format \
  --skip-fvm-install

# The bridge crate belongs to the repository-level Cargo workspace. A nested lockfile
# generated by the integration command would be misleading and is removed deliberately.
rm -f "$BRIDGE/Cargo.lock"

# Generate bindings from the real UnitFlow bridge API after native build scaffolding exists.
cd "$ROOT"
bash tool/generate_bridge.sh

echo "UnitFlow native FRB/Cargokit scaffolding and generated bindings are ready."
